[project]
name = "Flask-Alembic"
version = "3.0.0.dev"
description = "Flask extension to integrate Alembic with Flask-SQLAlchemy."
readme = "README.rst"
license = { file = "LICENSE.txt" }
authors = [{name = "David Lord", email = "davidism@gmail.com"},]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Database",
    "Typing :: Typed",
]
requires-python = ">=3.8"
dependencies = [
    "alembic>=1.13",
    "flask>=3.0",
    "flask-sqlalchemy>=3.1",
    "sqlalchemy>=2.0",
]

[project.urls]
Documentation = "https://flask-alembic.readthedocs.io"
Changes = "https://flask-alembic.readthedocs.io/#changes"
"Source Code" = "https://github.com/davidism/flask-alembic/"
"Issue Tracker" = "https://github.com/davidism/flask-alembic/issues/"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[tool.flit.module]
name = "flask_alembic"

[tool.pytest.ini_options]
testpaths = ["tests"]
filterwarnings = ["error"]

[tool.coverage.run]
branch = true
source = ["flask_alembic", "tests"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.mypy]
python_version = "3.8"
files = ["src/flask_alembic", "tests"]
show_error_codes = true
pretty = true
strict = true

[[tool.mypy.overrides]]
module = [
    "cryptography.*",
    "importlib_metadata.*",
]
ignore_missing_imports = true
